#![doc = r" Generated by `cargo xtask codegen` from `sass.ungram`."]
#![doc = r" Do not edit manually."]
#![allow(clippy::match_like_matches_macro)]
use crate::ast::{AstChildren, AstNode, support};
use crate::syntax::SyntaxNode;
use crate::syntax_kind::SyntaxKind;
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SourceFile {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for SourceFile {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SOURCE_FILE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl SourceFile {
    pub fn items(&self) -> AstChildren<Item> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RuleSet {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for RuleSet {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::RULE_SET
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl RuleSet {
    pub fn selectors(&self) -> Option<SelectorList> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Declaration {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Declaration {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::DECLARATION
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Declaration {
    pub fn name(&self) -> Option<Property> {
        support::child(&self.syntax)
    }
    pub fn value(&self) -> Option<Value> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CustomPropertyDecl {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for CustomPropertyDecl {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::CUSTOM_PROPERTY_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl CustomPropertyDecl {
    pub fn name(&self) -> Option<Property> {
        support::child(&self.syntax)
    }
    pub fn value(&self) -> Option<Value> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NestedProperty {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for NestedProperty {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::NESTED_PROPERTY
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl NestedProperty {
    pub fn name(&self) -> Option<Property> {
        support::child(&self.syntax)
    }
    pub fn value(&self) -> Option<Value> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct VariableDecl {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for VariableDecl {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::VARIABLE_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl VariableDecl {
    pub fn value(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn flags(&self) -> AstChildren<SassFlag> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MixinRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for MixinRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::MIXIN_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl MixinRule {
    pub fn params(&self) -> Option<ParamList> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct IncludeRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for IncludeRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::INCLUDE_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl IncludeRule {
    pub fn name(&self) -> Option<NamespaceRef> {
        support::child(&self.syntax)
    }
    pub fn args(&self) -> Option<ArgList> {
        support::child(&self.syntax)
    }
    pub fn using(&self) -> Option<ParamList> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ContentRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ContentRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::CONTENT_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ContentRule {
    pub fn args(&self) -> Option<ArgList> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct FunctionRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for FunctionRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::FUNCTION_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl FunctionRule {
    pub fn params(&self) -> Option<ParamList> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ReturnRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ReturnRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::RETURN_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ReturnRule {
    pub fn value(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct IfRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for IfRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::IF_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl IfRule {
    pub fn condition(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
    pub fn else_clauses(&self) -> AstChildren<ElseClause> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ForRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ForRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::FOR_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ForRule {
    pub fn from(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn to(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EachRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for EachRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::EACH_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl EachRule {
    pub fn iterable(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WhileRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for WhileRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::WHILE_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl WhileRule {
    pub fn condition(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ExtendRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ExtendRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::EXTEND_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ExtendRule {
    pub fn flag(&self) -> Option<SassFlag> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ErrorRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ErrorRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::ERROR_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ErrorRule {
    pub fn value(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WarnRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for WarnRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::WARN_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl WarnRule {
    pub fn value(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct DebugRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for DebugRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::DEBUG_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl DebugRule {
    pub fn value(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AtRootRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for AtRootRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::AT_ROOT_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl AtRootRule {
    pub fn query(&self) -> Option<AtRootQuery> {
        support::child(&self.syntax)
    }
    pub fn selectors(&self) -> Option<SelectorList> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MediaRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for MediaRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::MEDIA_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl MediaRule {
    pub fn queries(&self) -> AstChildren<MediaQuery> {
        support::children(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SupportsRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for SupportsRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SUPPORTS_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl SupportsRule {
    pub fn condition(&self) -> Option<SupportsCondition> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct KeyframesRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for KeyframesRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::KEYFRAMES_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl KeyframesRule {
    pub fn selectors(&self) -> AstChildren<KeyframeSelector> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct LayerRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for LayerRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::LAYER_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl LayerRule {
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ContainerRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ContainerRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::CONTAINER_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ContainerRule {
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ScopeRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ScopeRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SCOPE_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ScopeRule {
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PropertyRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for PropertyRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PROPERTY_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PropertyRule {
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NamespaceRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for NamespaceRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::NAMESPACE_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl NamespaceRule {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CharsetRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for CharsetRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::CHARSET_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl CharsetRule {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PageRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for PageRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PAGE_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PageRule {
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct FontFaceRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for FontFaceRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::FONT_FACE_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl FontFaceRule {
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UseRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for UseRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::USE_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl UseRule {
    pub fn arg_list(&self) -> Option<ArgList> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ForwardRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ForwardRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::FORWARD_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ForwardRule {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ImportRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ImportRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::IMPORT_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ImportRule {
    pub fn exprs(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GenericAtRule {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for GenericAtRule {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::GENERIC_AT_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl GenericAtRule {
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Block {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Block {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::BLOCK
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Block {
    pub fn items(&self) -> AstChildren<Item> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SelectorList {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for SelectorList {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SELECTOR_LIST
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl SelectorList {
    pub fn selectors(&self) -> AstChildren<Selector> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Selector {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Selector {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SELECTOR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Selector {
    pub fn parts(&self) -> AstChildren<SimpleSelector> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SimpleSelector {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for SimpleSelector {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SIMPLE_SELECTOR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl SimpleSelector {
    pub fn interpolation(&self) -> Option<Interpolation> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Interpolation {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Interpolation {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::INTERPOLATION
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Interpolation {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PseudoSelector {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for PseudoSelector {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PSEUDO_SELECTOR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PseudoSelector {
    pub fn args(&self) -> Option<SelectorList> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AttrSelector {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for AttrSelector {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::ATTR_SELECTOR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl AttrSelector {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Combinator {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Combinator {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::COMBINATOR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Combinator {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Property {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Property {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PROPERTY
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Property {
    pub fn interpolations(&self) -> AstChildren<Interpolation> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Value {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Value {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::VALUE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Value {
    pub fn exprs(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Important {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Important {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::IMPORTANT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Important {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SassFlag {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for SassFlag {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SASS_FLAG
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl SassFlag {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BinaryExpr {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for BinaryExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::BINARY_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl BinaryExpr {
    pub fn lhs(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn rhs(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UnaryExpr {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for UnaryExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::UNARY_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl UnaryExpr {
    pub fn operand(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ParenExpr {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ParenExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PAREN_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ParenExpr {
    pub fn inner(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NumberLiteral {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for NumberLiteral {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::NUMBER_LITERAL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl NumberLiteral {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Dimension {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Dimension {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::DIMENSION
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Dimension {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StringLiteral {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for StringLiteral {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::STRING_LITERAL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl StringLiteral {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct InterpolatedString {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for InterpolatedString {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::INTERPOLATED_STRING
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl InterpolatedString {
    pub fn interpolations(&self) -> AstChildren<Interpolation> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ColorLiteral {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ColorLiteral {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::COLOR_LITERAL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ColorLiteral {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BoolLiteral {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for BoolLiteral {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::BOOL_LITERAL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl BoolLiteral {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NullLiteral {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for NullLiteral {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::NULL_LITERAL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl NullLiteral {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ListExpr {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ListExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::LIST_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ListExpr {
    pub fn items(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BracketedList {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for BracketedList {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::BRACKETED_LIST
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl BracketedList {
    pub fn items(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MapExpr {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for MapExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::MAP_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl MapExpr {
    pub fn entries(&self) -> AstChildren<MapEntry> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct FunctionCall {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for FunctionCall {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::FUNCTION_CALL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl FunctionCall {
    pub fn args(&self) -> Option<ArgList> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Calculation {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Calculation {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::CALCULATION
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Calculation {
    pub fn args(&self) -> AstChildren<CalcSum> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SpecialFunctionCall {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for SpecialFunctionCall {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SPECIAL_FUNCTION_CALL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl SpecialFunctionCall {
    pub fn interpolations(&self) -> AstChildren<Interpolation> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct VariableRef {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for VariableRef {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::VARIABLE_REF
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl VariableRef {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NamespaceRef {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for NamespaceRef {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::NAMESPACE_REF
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl NamespaceRef {
    pub fn member(&self) -> Option<FunctionCall> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StandalonePercent {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for StandalonePercent {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::STANDALONE_PERCENT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl StandalonePercent {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MapEntry {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for MapEntry {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::MAP_ENTRY
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl MapEntry {
    pub fn key(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn value(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArgList {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ArgList {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::ARG_LIST
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ArgList {
    pub fn args(&self) -> AstChildren<Arg> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Arg {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Arg {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::ARG
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Arg {
    pub fn value(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CalcSum {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for CalcSum {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::CALC_SUM
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl CalcSum {
    pub fn calc_products(&self) -> AstChildren<CalcProduct> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CalcProduct {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for CalcProduct {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::CALC_PRODUCT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl CalcProduct {
    pub fn calc_values(&self) -> AstChildren<CalcValue> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CalcValue {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for CalcValue {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::CALC_VALUE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl CalcValue {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ParamList {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ParamList {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PARAM_LIST
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ParamList {
    pub fn params(&self) -> AstChildren<Param> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ElseClause {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for ElseClause {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::ELSE_CLAUSE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ElseClause {
    pub fn condition(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AtRootQuery {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for AtRootQuery {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::AT_ROOT_QUERY
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl AtRootQuery {}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MediaQuery {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for MediaQuery {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::MEDIA_QUERY
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl MediaQuery {
    pub fn interpolations(&self) -> AstChildren<Interpolation> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SupportsCondition {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for SupportsCondition {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SUPPORTS_CONDITION
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl SupportsCondition {
    pub fn interpolations(&self) -> AstChildren<Interpolation> {
        support::children(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct KeyframeSelector {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for KeyframeSelector {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::KEYFRAME_SELECTOR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl KeyframeSelector {
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Param {
    pub(crate) syntax: SyntaxNode,
}
impl AstNode for Param {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PARAM
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Param {
    pub fn default(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Item {
    RuleSet(RuleSet),
    Declaration(Declaration),
    CustomPropertyDecl(CustomPropertyDecl),
    NestedProperty(NestedProperty),
    VariableDecl(VariableDecl),
    MixinRule(MixinRule),
    IncludeRule(IncludeRule),
    ContentRule(ContentRule),
    FunctionRule(FunctionRule),
    ReturnRule(ReturnRule),
    IfRule(IfRule),
    ForRule(ForRule),
    EachRule(EachRule),
    WhileRule(WhileRule),
    ExtendRule(ExtendRule),
    ErrorRule(ErrorRule),
    WarnRule(WarnRule),
    DebugRule(DebugRule),
    AtRootRule(AtRootRule),
    MediaRule(MediaRule),
    SupportsRule(SupportsRule),
    KeyframesRule(KeyframesRule),
    LayerRule(LayerRule),
    ContainerRule(ContainerRule),
    ScopeRule(ScopeRule),
    PropertyRule(PropertyRule),
    NamespaceRule(NamespaceRule),
    CharsetRule(CharsetRule),
    PageRule(PageRule),
    FontFaceRule(FontFaceRule),
    UseRule(UseRule),
    ForwardRule(ForwardRule),
    ImportRule(ImportRule),
    GenericAtRule(GenericAtRule),
}
impl AstNode for Item {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            SyntaxKind::RULE_SET
                | SyntaxKind::DECLARATION
                | SyntaxKind::CUSTOM_PROPERTY_DECL
                | SyntaxKind::NESTED_PROPERTY
                | SyntaxKind::VARIABLE_DECL
                | SyntaxKind::MIXIN_RULE
                | SyntaxKind::INCLUDE_RULE
                | SyntaxKind::CONTENT_RULE
                | SyntaxKind::FUNCTION_RULE
                | SyntaxKind::RETURN_RULE
                | SyntaxKind::IF_RULE
                | SyntaxKind::FOR_RULE
                | SyntaxKind::EACH_RULE
                | SyntaxKind::WHILE_RULE
                | SyntaxKind::EXTEND_RULE
                | SyntaxKind::ERROR_RULE
                | SyntaxKind::WARN_RULE
                | SyntaxKind::DEBUG_RULE
                | SyntaxKind::AT_ROOT_RULE
                | SyntaxKind::MEDIA_RULE
                | SyntaxKind::SUPPORTS_RULE
                | SyntaxKind::KEYFRAMES_RULE
                | SyntaxKind::LAYER_RULE
                | SyntaxKind::CONTAINER_RULE
                | SyntaxKind::SCOPE_RULE
                | SyntaxKind::PROPERTY_RULE
                | SyntaxKind::NAMESPACE_RULE
                | SyntaxKind::CHARSET_RULE
                | SyntaxKind::PAGE_RULE
                | SyntaxKind::FONT_FACE_RULE
                | SyntaxKind::USE_RULE
                | SyntaxKind::FORWARD_RULE
                | SyntaxKind::IMPORT_RULE
                | SyntaxKind::GENERIC_AT_RULE
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        let res = match syntax.kind() {
            SyntaxKind::RULE_SET => Item::RuleSet(RuleSet { syntax }),
            SyntaxKind::DECLARATION => Item::Declaration(Declaration { syntax }),
            SyntaxKind::CUSTOM_PROPERTY_DECL => {
                Item::CustomPropertyDecl(CustomPropertyDecl { syntax })
            }
            SyntaxKind::NESTED_PROPERTY => Item::NestedProperty(NestedProperty { syntax }),
            SyntaxKind::VARIABLE_DECL => Item::VariableDecl(VariableDecl { syntax }),
            SyntaxKind::MIXIN_RULE => Item::MixinRule(MixinRule { syntax }),
            SyntaxKind::INCLUDE_RULE => Item::IncludeRule(IncludeRule { syntax }),
            SyntaxKind::CONTENT_RULE => Item::ContentRule(ContentRule { syntax }),
            SyntaxKind::FUNCTION_RULE => Item::FunctionRule(FunctionRule { syntax }),
            SyntaxKind::RETURN_RULE => Item::ReturnRule(ReturnRule { syntax }),
            SyntaxKind::IF_RULE => Item::IfRule(IfRule { syntax }),
            SyntaxKind::FOR_RULE => Item::ForRule(ForRule { syntax }),
            SyntaxKind::EACH_RULE => Item::EachRule(EachRule { syntax }),
            SyntaxKind::WHILE_RULE => Item::WhileRule(WhileRule { syntax }),
            SyntaxKind::EXTEND_RULE => Item::ExtendRule(ExtendRule { syntax }),
            SyntaxKind::ERROR_RULE => Item::ErrorRule(ErrorRule { syntax }),
            SyntaxKind::WARN_RULE => Item::WarnRule(WarnRule { syntax }),
            SyntaxKind::DEBUG_RULE => Item::DebugRule(DebugRule { syntax }),
            SyntaxKind::AT_ROOT_RULE => Item::AtRootRule(AtRootRule { syntax }),
            SyntaxKind::MEDIA_RULE => Item::MediaRule(MediaRule { syntax }),
            SyntaxKind::SUPPORTS_RULE => Item::SupportsRule(SupportsRule { syntax }),
            SyntaxKind::KEYFRAMES_RULE => Item::KeyframesRule(KeyframesRule { syntax }),
            SyntaxKind::LAYER_RULE => Item::LayerRule(LayerRule { syntax }),
            SyntaxKind::CONTAINER_RULE => Item::ContainerRule(ContainerRule { syntax }),
            SyntaxKind::SCOPE_RULE => Item::ScopeRule(ScopeRule { syntax }),
            SyntaxKind::PROPERTY_RULE => Item::PropertyRule(PropertyRule { syntax }),
            SyntaxKind::NAMESPACE_RULE => Item::NamespaceRule(NamespaceRule { syntax }),
            SyntaxKind::CHARSET_RULE => Item::CharsetRule(CharsetRule { syntax }),
            SyntaxKind::PAGE_RULE => Item::PageRule(PageRule { syntax }),
            SyntaxKind::FONT_FACE_RULE => Item::FontFaceRule(FontFaceRule { syntax }),
            SyntaxKind::USE_RULE => Item::UseRule(UseRule { syntax }),
            SyntaxKind::FORWARD_RULE => Item::ForwardRule(ForwardRule { syntax }),
            SyntaxKind::IMPORT_RULE => Item::ImportRule(ImportRule { syntax }),
            SyntaxKind::GENERIC_AT_RULE => Item::GenericAtRule(GenericAtRule { syntax }),
            _ => return None,
        };
        Some(res)
    }
    fn syntax(&self) -> &SyntaxNode {
        match self {
            Item::RuleSet(it) => &it.syntax,
            Item::Declaration(it) => &it.syntax,
            Item::CustomPropertyDecl(it) => &it.syntax,
            Item::NestedProperty(it) => &it.syntax,
            Item::VariableDecl(it) => &it.syntax,
            Item::MixinRule(it) => &it.syntax,
            Item::IncludeRule(it) => &it.syntax,
            Item::ContentRule(it) => &it.syntax,
            Item::FunctionRule(it) => &it.syntax,
            Item::ReturnRule(it) => &it.syntax,
            Item::IfRule(it) => &it.syntax,
            Item::ForRule(it) => &it.syntax,
            Item::EachRule(it) => &it.syntax,
            Item::WhileRule(it) => &it.syntax,
            Item::ExtendRule(it) => &it.syntax,
            Item::ErrorRule(it) => &it.syntax,
            Item::WarnRule(it) => &it.syntax,
            Item::DebugRule(it) => &it.syntax,
            Item::AtRootRule(it) => &it.syntax,
            Item::MediaRule(it) => &it.syntax,
            Item::SupportsRule(it) => &it.syntax,
            Item::KeyframesRule(it) => &it.syntax,
            Item::LayerRule(it) => &it.syntax,
            Item::ContainerRule(it) => &it.syntax,
            Item::ScopeRule(it) => &it.syntax,
            Item::PropertyRule(it) => &it.syntax,
            Item::NamespaceRule(it) => &it.syntax,
            Item::CharsetRule(it) => &it.syntax,
            Item::PageRule(it) => &it.syntax,
            Item::FontFaceRule(it) => &it.syntax,
            Item::UseRule(it) => &it.syntax,
            Item::ForwardRule(it) => &it.syntax,
            Item::ImportRule(it) => &it.syntax,
            Item::GenericAtRule(it) => &it.syntax,
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Expr {
    BinaryExpr(BinaryExpr),
    UnaryExpr(UnaryExpr),
    ParenExpr(ParenExpr),
    NumberLiteral(NumberLiteral),
    Dimension(Dimension),
    StringLiteral(StringLiteral),
    InterpolatedString(InterpolatedString),
    ColorLiteral(ColorLiteral),
    BoolLiteral(BoolLiteral),
    NullLiteral(NullLiteral),
    ListExpr(ListExpr),
    BracketedList(BracketedList),
    MapExpr(MapExpr),
    FunctionCall(FunctionCall),
    Calculation(Calculation),
    SpecialFunctionCall(SpecialFunctionCall),
    VariableRef(VariableRef),
    NamespaceRef(NamespaceRef),
    StandalonePercent(StandalonePercent),
}
impl AstNode for Expr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            SyntaxKind::BINARY_EXPR
                | SyntaxKind::UNARY_EXPR
                | SyntaxKind::PAREN_EXPR
                | SyntaxKind::NUMBER_LITERAL
                | SyntaxKind::DIMENSION
                | SyntaxKind::STRING_LITERAL
                | SyntaxKind::INTERPOLATED_STRING
                | SyntaxKind::COLOR_LITERAL
                | SyntaxKind::BOOL_LITERAL
                | SyntaxKind::NULL_LITERAL
                | SyntaxKind::LIST_EXPR
                | SyntaxKind::BRACKETED_LIST
                | SyntaxKind::MAP_EXPR
                | SyntaxKind::FUNCTION_CALL
                | SyntaxKind::CALCULATION
                | SyntaxKind::SPECIAL_FUNCTION_CALL
                | SyntaxKind::VARIABLE_REF
                | SyntaxKind::NAMESPACE_REF
                | SyntaxKind::STANDALONE_PERCENT
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        let res = match syntax.kind() {
            SyntaxKind::BINARY_EXPR => Expr::BinaryExpr(BinaryExpr { syntax }),
            SyntaxKind::UNARY_EXPR => Expr::UnaryExpr(UnaryExpr { syntax }),
            SyntaxKind::PAREN_EXPR => Expr::ParenExpr(ParenExpr { syntax }),
            SyntaxKind::NUMBER_LITERAL => Expr::NumberLiteral(NumberLiteral { syntax }),
            SyntaxKind::DIMENSION => Expr::Dimension(Dimension { syntax }),
            SyntaxKind::STRING_LITERAL => Expr::StringLiteral(StringLiteral { syntax }),
            SyntaxKind::INTERPOLATED_STRING => {
                Expr::InterpolatedString(InterpolatedString { syntax })
            }
            SyntaxKind::COLOR_LITERAL => Expr::ColorLiteral(ColorLiteral { syntax }),
            SyntaxKind::BOOL_LITERAL => Expr::BoolLiteral(BoolLiteral { syntax }),
            SyntaxKind::NULL_LITERAL => Expr::NullLiteral(NullLiteral { syntax }),
            SyntaxKind::LIST_EXPR => Expr::ListExpr(ListExpr { syntax }),
            SyntaxKind::BRACKETED_LIST => Expr::BracketedList(BracketedList { syntax }),
            SyntaxKind::MAP_EXPR => Expr::MapExpr(MapExpr { syntax }),
            SyntaxKind::FUNCTION_CALL => Expr::FunctionCall(FunctionCall { syntax }),
            SyntaxKind::CALCULATION => Expr::Calculation(Calculation { syntax }),
            SyntaxKind::SPECIAL_FUNCTION_CALL => {
                Expr::SpecialFunctionCall(SpecialFunctionCall { syntax })
            }
            SyntaxKind::VARIABLE_REF => Expr::VariableRef(VariableRef { syntax }),
            SyntaxKind::NAMESPACE_REF => Expr::NamespaceRef(NamespaceRef { syntax }),
            SyntaxKind::STANDALONE_PERCENT => Expr::StandalonePercent(StandalonePercent { syntax }),
            _ => return None,
        };
        Some(res)
    }
    fn syntax(&self) -> &SyntaxNode {
        match self {
            Expr::BinaryExpr(it) => &it.syntax,
            Expr::UnaryExpr(it) => &it.syntax,
            Expr::ParenExpr(it) => &it.syntax,
            Expr::NumberLiteral(it) => &it.syntax,
            Expr::Dimension(it) => &it.syntax,
            Expr::StringLiteral(it) => &it.syntax,
            Expr::InterpolatedString(it) => &it.syntax,
            Expr::ColorLiteral(it) => &it.syntax,
            Expr::BoolLiteral(it) => &it.syntax,
            Expr::NullLiteral(it) => &it.syntax,
            Expr::ListExpr(it) => &it.syntax,
            Expr::BracketedList(it) => &it.syntax,
            Expr::MapExpr(it) => &it.syntax,
            Expr::FunctionCall(it) => &it.syntax,
            Expr::Calculation(it) => &it.syntax,
            Expr::SpecialFunctionCall(it) => &it.syntax,
            Expr::VariableRef(it) => &it.syntax,
            Expr::NamespaceRef(it) => &it.syntax,
            Expr::StandalonePercent(it) => &it.syntax,
        }
    }
}
